namespace Flaeng.Productivity.Generators;

[Generator(LanguageNames.CSharp)]
public sealed partial class InterfaceGenerator : GeneratorBase
{
    public override void Initialize(IncrementalGeneratorInitializationContext context)
    {
        Initialize(context, GenerateTriggerAttribute, Predicate, Transform, InterfaceDataEqualityComparer.Instance, Execute);
    }

    public static bool Predicate(SyntaxNode node, CancellationToken ct)
    {
        if (node is not ClassDeclarationSyntax { AttributeLists.Count: > 0 } cds)
            return false;

        return HasTriggerAttribute(cds);
    }

    private static void GenerateTriggerAttribute(IncrementalGeneratorPostInitializationContext context)
    {
        context.AddSource("GenerateInterfaceAttribute.g.cs", SourceText.From($$"""
        // <auto-generated/>

        #nullable enable

        namespace Flaeng
        {
            {{Constants.GeneratedCodeAttribute}}
            internal enum Visibility { Default, Public, Internal }

            [global::System.AttributeUsageAttribute(
                global::System.AttributeTargets.Class,
                AllowMultiple = false,
                Inherited = false)]
            {{Constants.GeneratedCodeAttribute}}
            internal sealed class GenerateInterfaceAttribute : global::System.Attribute
            {
                public string? Name = null;
                public Visibility Visibility = Visibility.Default;
            }
        }
        """, Encoding.UTF8));
    }
}
