namespace Flaeng.Productivity.Tests;

public static class Constants
{
    public const string TriggerAttributeContentPrefix = $"""
        // <auto-generated/>

        #nullable enable
        """;

    public const string GeneratedContentPrefix = $"""
        // <auto-generated/>

        #nullable enable

        #pragma warning disable CS8019
        """;

    public const string GeneratedCodeAttribute = """
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Flaeng.Productivity", "0.3.0.0")]
    """;

    public static readonly string ConstructorGeneratorGeneratedContentPathPrefix =
        $"Flaeng.Productivity{Path.DirectorySeparatorChar}Flaeng.Productivity.Generators.ConstructorGenerator{Path.DirectorySeparatorChar}";

    public static readonly string InterfaceGeneratorGeneratedContentPathPrefix =
        $"Flaeng.Productivity{Path.DirectorySeparatorChar}Flaeng.Productivity.Generators.InterfaceGenerator{Path.DirectorySeparatorChar}";


    public static readonly string StartupGeneratorGeneratedContentPathPrefix =
        $"Flaeng.Productivity{Path.DirectorySeparatorChar}Flaeng.Productivity.Generators.StartupGenerator{Path.DirectorySeparatorChar}";


    public static readonly string FluentApiGeneratorGeneratedContentPathPrefix =
        $"Flaeng.Productivity{Path.DirectorySeparatorChar}Flaeng.Productivity.Generators.FluentApiGenerator{Path.DirectorySeparatorChar}";

}
