namespace Flaeng.Productivity.Tests;

public static class Constants
{
    public const string TriggerAttributeContentPrefix = $"""
        // <auto-generated/>

        #nullable enable
        """;

    public const string GeneratedContentPrefix = $"""
        // <auto-generated/>

        #nullable enable

        #pragma warning disable CS8019
        """;

    public const string GeneratedCodeAttribute = """
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Flaeng.Productivity", "0.3.0.0")]
    """;

    public const string ConstructorGeneratorGeneratedContentPathPrefix = 
        @"Flaeng.Productivity\Flaeng.Productivity.Generators.ConstructorGenerator\";
        
    public const string InterfaceGeneratorGeneratedContentPathPrefix = 
        @"Flaeng.Productivity\Flaeng.Productivity.Generators.InterfaceGenerator\";
        
        
    public const string StartupGeneratorGeneratedContentPathPrefix = 
        @"Flaeng.Productivity\Flaeng.Productivity.Generators.StartupGenerator\";
        
        
    public const string FluentApiGeneratorGeneratedContentPathPrefix = 
        @"Flaeng.Productivity\Flaeng.Productivity.Generators.FluentApiGenerator\";
        
}
