name: Build and run tests

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Build
        run: dotnet build

      - name: Run tests
        run: dotnet test

      - name: Install Stryker.NET
        run: dotnet tool install -g dotnet-stryker

      - name: Run Stryker.NET
        run: dotnet stryker -l "Advanced"

      - name: Upload Stryker Report
        uses: actions/upload-artifact@v3
        with:
          name: stryker-report
          path: StrykerOutput/**/mutation-report.html
